-- Create sequence for P_JOB_TYPE_ID
CREATE SEQUENCE SEQ_P_JOB_TYPE
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Create P_JOB_TYPE table
CREATE TABLE P_JOB_TYPE (
    P_JOB_TYPE_ID NUMBER(38,0) NOT NULL,
    CODE VARCHAR2(128) NOT NULL,
    DESCRIPTION VARCHAR2(512),
    UPDATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR2(128) NOT NULL,
    CONSTRAINT PK_P_JOB_TYPE PRIMARY KEY (P_JOB_TYPE_ID)
);

-- Create unique index on CODE
CREATE UNIQUE INDEX UK_P_JOB_TYPE_CODE ON P_JOB_TYPE (CODE);
