name: Unit Tests Only

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run Non-JPA Tests
      run: |
        echo "🧪 Running Non-JPA unit tests..."
        ./mvnw test -Dtest=PJobTypeControllerBasicTest,PJobTypeServiceSimpleTest,DatabaseInitializationServiceTest

    - name: Run JPA Tests
      run: |
        echo "🧪 Running JPA unit tests..."
        ./mvnw test -Dtest=PJobTypeJpaControllerTest,PJobTypeJpaServiceTest

    - name: Run All Tests
      run: |
        echo "🧪 Running all tests..."
        ./mvnw test

    - name: Generate Coverage Report
      run: |
        echo "📊 Generating coverage report..."
        ./mvnw jacoco:report

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ github.run_number }}
        path: |
          target/surefire-reports/
          target/site/jacoco/

    - name: Test Results Summary
      if: always()
      run: |
        echo "## 🧪 Test Results Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ✅ Tests Executed:" >> $GITHUB_STEP_SUMMARY
        echo "- **Non-JPA Tests**: Controller & Service tests" >> $GITHUB_STEP_SUMMARY
        echo "- **JPA Tests**: Controller & Service tests (46 total)" >> $GITHUB_STEP_SUMMARY
        echo "- **Coverage Report**: Generated successfully" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📊 Artifacts:" >> $GITHUB_STEP_SUMMARY
        echo "- Test reports: \`target/surefire-reports/\`" >> $GITHUB_STEP_SUMMARY
        echo "- Coverage report: \`target/site/jacoco/\`" >> $GITHUB_STEP_SUMMARY
